#!/usr/bin/env python3
"""Generate microsegmentation-policies.yaml without YAML anchors (kubectl-safe)."""
from pathlib import Path

NS = "clab-3-tier-leaf-spine-dcgw"

RBG = [
    # Same-group: required for self / intra-group traffic (not covered by cross-group allows).
    ("allow same-group red", [("red", "red")], "Accept", False),
    ("allow blue-blue", [("blue", "blue")], "Accept", False),
    ("allow green-green", [("green", "green")], "Accept", False),
    # Minimal cross-group chain: red<->blue and blue<->green (bidirectional on each entry).
    ("allow red to/from blue", [("red", "blue")], "Accept", False),
    ("allow blue to/from green", [("blue", "green")], "Accept", False),
    # Explicit red<->green drop: redundant with deny-default for enforcement; kept for
    # entry counters + log:true on this pair (see docs §3.5).
    ("block red to/from green", [("red", "green")], "Drop", True),
    ("default deny", [], "Drop", False),
]

def entry(desc, tags, forward, log):
    if not tags:
        return {
            "description": desc,
            "bidirectional": True,
            "match": {},
            "action": {"forward": forward, "collectStats": True, "log": log},
        }
    s, d = tags[0]
    return {
        "description": desc,
        "bidirectional": True,
        "match": {"sourceGroupTag": [s], "destinationGroupTag": [d]},
        "action": {"forward": forward, "collectStats": True, "log": log},
    }

def policy(name, variant, desc, targets, entries):
    return {
        "apiVersion": "microsegmentation.eda.nokia.com/v1alpha1",
        "kind": "MicroSegmentationPolicy",
        "metadata": {
            "name": name,
            "namespace": NS,
            "labels": {"eda.nokia.com/ms-variant": variant},
            "annotations": {"eda.nokia.com/ms-demo-description": desc},
        },
        "spec": {"serviceTargets": targets, "entries": entries},
    }

import yaml

policies = [
    policy(
        "ms-policy-vlan",
        "vlan-association",
        "Policy for vnet-ms-vlan — serviceTargets.virtualNetworks",
        {"virtualNetworks": ["vnet-ms-vlan"]},
        [entry(*r) for r in RBG],
    ),
    policy(
        "ms-policy-bridge",
        "bridge-interface-association",
        "Policy for vnet-ms-bridge — serviceTargets.virtualNetworks",
        {"virtualNetworks": ["vnet-ms-bridge"]},
        [entry(*r) for r in RBG],
    ),
    policy(
        "ms-policy-routed",
        "routed-interface-association",
        "Policy for vnet-ms-routed — serviceTargets.virtualNetworks",
        {"virtualNetworks": ["vnet-ms-routed"]},
        [entry(*r) for r in RBG],
    ),
    policy(
        "ms-policy-static",
        "static-route-association",
        "Policy for vnet-ms-static — red->172.16.205.x blocked via static-route green tag",
        {"virtualNetworks": ["vnet-ms-static"]},
        [entry(*r) for r in RBG],
    ),
    policy(
        "ms-policy-enf-router",
        "enforcement-router-target",
        "Policy for vnet-ms-enf-router — serviceTargets.routers only",
        {"routers": ["router-ms-enf-router"]},
        [entry(*r) for r in RBG],
    ),
    policy(
        "ms-policy-enf-bd",
        "enforcement-bridge-domain-target",
        "Policy for vnet-ms-enf-bd — serviceTargets.bridgeDomains only (L2)",
        {"bridgeDomains": ["bd-ms-enf-bd"]},
        [entry(*r) for r in RBG],
    ),
    policy(
        "ms-policy-irb",
        "irb-interface-association",
        "Policy for vnet-ms-irb — gateway IRB rules + host rules",
        {"virtualNetworks": ["vnet-ms-irb"]},
        [
            entry("allow red to/from gateway IRB", [("red", "gateway")], "Accept", False),
            entry("allow blue to/from gateway IRB", [("blue", "gateway")], "Accept", False),
            entry("allow green to/from gateway IRB", [("green", "gateway")], "Accept", False),
        ] + [entry(*r) for r in RBG],
    ),
]

out = Path(__file__).resolve().parent / "microsegmentation-policies.yaml"
with out.open("w", encoding="utf-8") as f:
    f.write("# Generated by gen-microsegmentation-policies.py — do not edit by hand\n")
    for p in policies:
        f.write("---\n")
        yaml.safe_dump(p, f, sort_keys=False)

print(f"Wrote {out}")
