apiVersion: microsegmentation.eda.nokia.com/v1alpha1
kind: MicroSegmentationPolicy
metadata:
  name: red-blue-green
  namespace: clab-3-tier-leaf-spine-dcgw
  labels:
    eda.nokia.com/gbp: red-blue-green
spec:
  serviceTargets:
    virtualNetworks:
      - vnet-1
  entries:
    - description: allow same-group traffic
      bidirectional: true
      match:
        sourceGroupTag:
          - red
        destinationGroupTag:
          - red
      action:
        forward: Accept
        collectStats: true
        log: false
    - description: allow blue-blue
      bidirectional: true
      match:
        sourceGroupTag:
          - blue
        destinationGroupTag:
          - blue
      action:
        forward: Accept
        collectStats: true
        log: false
    - description: allow green-green
      bidirectional: true
      match:
        sourceGroupTag:
          - green
        destinationGroupTag:
          - green
      action:
        forward: Accept
        collectStats: true
        log: false
    - description: allow red to/from blue
      bidirectional: true
      match:
        sourceGroupTag:
          - red
        destinationGroupTag:
          - blue
      action:
        forward: Accept
        collectStats: true
        log: false
    - description: allow blue to/from green
      bidirectional: true
      match:
        sourceGroupTag:
          - blue
        destinationGroupTag:
          - green
      action:
        forward: Accept
        collectStats: true
        log: false
    - description: block red to/from green
      bidirectional: true
      match:
        sourceGroupTag:
          - red
        destinationGroupTag:
          - green
      action:
        forward: Drop
        collectStats: true
        log: true
    - description: default deny other cross-segment traffic
      bidirectional: true
      match: {}
      action:
        forward: Drop
        collectStats: true
        log: false
